//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 * @param <R>
 */
public class Temp_count<R> extends DepthFirstVisitor {
	public int max_Temp = 0;
	/**
	 * f0 -> "TEMP"
	 * f1 -> IntegerLiteral()
	 * @return 
	 */
	public void visit(Temp n) {
		if(Integer.decode(n.f1.f0.tokenImage) > max_Temp)
			  max_Temp = Integer.decode(n.f1.f0.tokenImage);
		   
		  n.f0.accept(this);
	      n.f1.accept(this);
		
		
		
	}
}
